stages:
  - test
  - perf
  - cleanup

variables:
  PACK_RULE: package

.develope_only_template:
  only:
    - branches
    - schedules
    - external_pull_requests
    - merge_requests

.full_only_template:
  only:
    - /^.*-full-ci$/
    - schedules
    - external_pull_requests
    - merge_requests

.pack_only_template:
  extends: .full_only_template

.perf_only_template:
  only:
    - /^.*-full-ci-perf$/
    - /^.*-perf$/
    - external_pull_requests
    - merge_requests
  except:
    - schedules

# Jobs templates

include:
  - '.templates.gitlab-ci.yml'
  - '.perf.gitlab-ci.yml'

# Tests release and debug

builds:release:
  extends:
    - .develope_only_template
    - .test_release_template

builds:debug:
  extends:
    - .develope_only_template
    - .test_debug_template

# Clang builds (Clang/Clang+LTO/Clang8+LTO/Clang8+ASAN)

clang:release:
  extends:
    - .develope_only_template
    - .test_release_clang_template

clang:release_lto:
  extends:
    - .full_only_template
    - .test_release_lto_template

clang:v8_release_lto:
  extends:
    - .full_only_template
    - .test_release_lto_clang8_template

clang:v8_release_asan:
  extends:
    - .develope_only_template
    - .test_release_asan_clang8_template

# Static builds w/ & w/o dockerfile

builds:static:
  extends:
    - .develope_only_template
    - .test_static_build_template

builds:static_docker:
  extends:
    - .full_only_template
    - .test_static_docker_build_template

# OSX builds (14/15/15+LTO)

osx:14_release:
  extends:
    - .full_only_template
    - .test_osx_14_release_template

osx:15_release:
  extends:
    - .develope_only_template
    - .test_osx_15_release_template

osx:15_release_lto:
  extends:
    - .full_only_template
    - .test_osx_15_release_lto_template

# FreeBSD build

freebsd:12_release:
  extends:
    - .develope_only_template
    - .test_freebsd_12_release_template

# Build only packages and sources

pack:sources:
  extends: .pack_template
  script:
    - ${GITLAB_MAKE} source

pack:centos_6:
  extends: .test_centos_6_template

pack:centos_7:
  extends: .test_centos_7_template

pack:centos_8:
  extends: .test_centos_8_template

pack:fedora_28:
  extends: .test_fedora_28_template

pack:fedora_29:
  extends: .test_fedora_29_template

pack:fedora_30:
  extends: .test_fedora_30_template

pack:fedora_31:
  extends: .test_fedora_31_template

pack:ubuntu_14_04:
  extends: .test_ubuntu_14_04_template

pack:ubuntu_16_04:
  extends: .test_ubuntu_16_04_template

pack:ubuntu_18_04:
  extends: .test_ubuntu_18_04_template

pack:ubuntu_19_10:
  extends: .test_ubuntu_19_10_template

pack:ubuntu_20_04:
  extends: .test_ubuntu_20_04_template

pack:debian_8:
  extends: .test_debian_8_template

pack:debian_9:
  extends: .test_debian_9_template

pack:debian_10:
  extends: .test_debian_10_template
