stages:
  - test
  - perf
  - cleanup

variables:
  PACK_RULE: deploy

.release_only_template:
  only:
    - master
    - /^.*branches-gitlab-ci$/
    - schedules

.pack_only_template:
  extends: .release_only_template

.perf_only_template:
  only:
    - master
    - /^.*branches-gitlab-ci$/
  except:
    - schedules

# Jobs templates

include:
  - '.templates.gitlab-ci.yml'
  - '.perf.gitlab-ci.yml'

# Tests release and debug

builds:release:
  extends:
    - .release_only_template
    - .test_release_template

builds:debug:
  extends:
    - .release_only_template
    - .test_debug_template

# Clang builds (Clang/Clang+LTO/Clang8+LTO/Clang8+ASAN)

clang:release:
  extends:
    - .release_only_template
    - .test_release_clang_template

clang:release_lto:
  extends:
    - .release_only_template
    - .test_release_lto_template

clang:v8_release_lto:
  extends:
    - .release_only_template
    - .test_release_lto_clang8_template

clang:v8_release_asan:
  extends:
    - .release_only_template
    - .test_release_asan_clang8_template

# Static builds w/ & w/o dockerfile

builds:static:
  extends:
    - .release_only_template
    - .test_static_build_template

builds:static_docker:
  extends:
    - .release_only_template
    - .test_static_docker_build_template

# OSX builds (14/15/15+LTO)

osx:14_release:
  extends:
    - .release_only_template
    - .test_osx_14_release_template

osx:15_release:
  extends:
    - .release_only_template
    - .test_osx_15_release_template

osx:15_release_lto:
  extends:
    - .release_only_template
    - .test_osx_15_release_lto_template

# FreeBSD build

freebsd:12_release:
  extends:
    - .release_only_template
    - .test_freebsd_12_release_template

# Build and deploy packages and sources

deploy:sources:
  extends: .pack_template
  script:
    - ${GITLAB_MAKE} source_deploy

deploy:centos_6:
  extends: .test_centos_6_template

deploy:centos_7:
  extends: .test_centos_7_template

deploy:centos_8:
  extends: .test_centos_8_template

deploy:fedora_28:
  extends: .test_fedora_28_template

deploy:fedora_29:
  extends: .test_fedora_29_template

deploy:fedora_30:
  extends: .test_fedora_30_template

deploy:fedora_31:
  extends: .test_fedora_31_template

deploy:ubuntu_14_04:
  extends: .test_ubuntu_14_04_template

deploy:ubuntu_16_04:
  extends: .test_ubuntu_16_04_template

deploy:ubuntu_18_04:
  extends: .test_ubuntu_18_04_template

deploy:ubuntu_19_10:
  extends: .test_ubuntu_19_10_template

deploy:ubuntu_20_04:
  extends: .test_ubuntu_20_04_template

deploy:debian_8:
  extends: .test_debian_8_template

deploy:debian_9:
  extends: .test_debian_9_template

deploy:debian_10:
  extends: .test_debian_10_template
