stages:
  - test
  - perf
  - cleanup

variables:
  PACK_RULE: deploy

.release_only_template:
  only:
    - master
    - /^.*branches-gitlab-ci$/
    - schedules

.pack_only_template:
  extends: .release_only_template

.perf_only_template:
  only:
    - master
    - /^.*branches-gitlab-ci$/
  except:
    - schedules

# Jobs templates

include:
  - '.templates.gitlab-ci.yml'
  - '.perf.gitlab-ci.yml'

# Tests release and debug

release:
  extends:
    - .release_only_template
    - .test_release_template

debug:
  extends:
    - .release_only_template
    - .test_debug_template

# Clang builds (Clang/Clang+LTO/Clang8+LTO/Clang8+ASAN)

release_clang:
  extends:
    - .release_only_template
    - .test_release_clang_template

release_lto:
  extends:
    - .release_only_template
    - .test_release_lto_template

release_lto_clang8:
  extends:
    - .release_only_template
    - .test_release_lto_clang8_template

release_asan_clang8:
  extends:
    - .release_only_template
    - .test_release_asan_clang8_template

# Static builds w/ & w/o dockerfile

static_build:
  extends:
    - .release_only_template
    - .test_static_build_template

static_docker_build:
  extends:
    - .release_only_template
    - .test_static_docker_build_template

# OSX builds (14/15/15+LTO)

osx_14_release:
  extends:
    - .release_only_template
    - .test_osx_14_release_template

osx_15_release:
  extends:
    - .release_only_template
    - .test_osx_15_release_template

osx_15_release_lto:
  extends:
    - .release_only_template
    - .test_osx_15_release_lto_template

# FreeBSD build

freebsd_12_release:
  extends:
    - .release_only_template
    - .test_freebsd_12_release_template

# Build and deploy packages and sources

sources_deploy:
  extends: .pack_template
  script:
    - ${GITLAB_MAKE} source_deploy

centos_6_deploy:
  extends: .test_centos_6_template

centos_7_deploy:
  extends: .test_centos_7_template

centos_8_deploy:
  extends: .test_centos_8_template

fedora_28_deploy:
  extends: .test_fedora_28_template

fedora_29_deploy:
  extends: .test_fedora_29_template

fedora_30_deploy:
  extends: .test_fedora_30_template

fedora_31_deploy:
  extends: .test_fedora_31_template

ubuntu_14_04_deploy:
  extends: .test_ubuntu_14_04_template

ubuntu_16_04_deploy:
  extends: .test_ubuntu_16_04_template

ubuntu_18_04_deploy:
  extends: .test_ubuntu_18_04_template

ubuntu_19_10_deploy:
  extends: .test_ubuntu_19_10_template

ubuntu_20_04_deploy:
  extends: .test_ubuntu_20_04_template

debian_8_deploy:
  extends: .test_debian_8_template

debian_9_deploy:
  extends: .test_debian_9_template

debian_10_deploy:
  extends: .test_debian_10_template
